#!/usr/bin/env bash
# Capture Projects v2 field + option IDs into scripts/.project-ids.env.
# Reads owner + project number from .claude/kit.config.json. Run from project root.
# Handles "Status", "Role", and "Plan Link" fields by name (case-insensitive).
set -euo pipefail
source "$(dirname "$0")/lib/kit-config.sh" && load_kit_config

[[ "$KIT_PROJECTS_V2" != "true" ]] && { echo "Projects v2 not enabled for this project — nothing to capture."; exit 0; }

OUT="$(dirname "$0")/.project-ids.env"

DATA=$(gh api graphql -f query='
  query($login:String!, $number:Int!){
    user(login:$login){
      projectV2(number:$number){
        id
        fields(first:50){ nodes{
          __typename
          ... on ProjectV2FieldCommon { id name }
          ... on ProjectV2SingleSelectField { id name options { id name } }
        }}
      }
    }
  }' -f login="$KIT_OWNER" -F number="$KIT_PROJECT_NUMBER")

PROJECT_ID=$(echo "$DATA" | jq -r '.data.user.projectV2.id')
[[ -z "$PROJECT_ID" || "$PROJECT_ID" == "null" ]] && { echo "✗ Could not resolve project #$KIT_PROJECT_NUMBER for $KIT_OWNER"; exit 1; }

# jq filter: normalize an option/field label -> UPPER_SNAKE
norm='def n: ascii_upcase | gsub("[ -]";"_");'

{
  echo "# Generated by capture-project-ids.sh — do not edit by hand."
  echo "PROJECT_ID=$PROJECT_ID"

  # Single-select fields -> <FIELD>_FIELD_ID + <FIELD>_OPT_<OPTION>
  echo "$DATA" | jq -r "$norm"'
    .data.user.projectV2.fields.nodes[]
    | select(.options != null)
    | (.name | n) as $f
    | ([ "\($f)_FIELD_ID=\(.id)" ]
       + (.options[] | "\($f)_OPT_\(.name | n)=\(.id)" | [.])) []'

  # Text/other fields -> <FIELD>_FIELD_ID
  echo "$DATA" | jq -r "$norm"'
    .data.user.projectV2.fields.nodes[]
    | select(.options == null) | select(.name != null)
    | "\(.name | n)_FIELD_ID=\(.id)"'
} > "$OUT"

echo "✓ Wrote $OUT"
echo "  Fields captured:"
grep -E '_FIELD_ID=' "$OUT" | sed 's/^/    /'
