#!/usr/bin/env bash
# skill-frontmatter-lint.sh — context-budget guardrail for skill frontmatter (kit-owned).
#
# WHY: Claude Code concatenates a skill's `description` + `when_to_use` into the always-loaded
# skill listing. Both fields sit in every session's context whether or not the skill is ever
# invoked — only the SKILL.md *body* is lazy. Unbudgeted, these fields grow into second bodies:
# the listing text is rent paid on every turn, and past a harness cap the tail is silently
# truncated, so an over-long field costs tokens while delivering nothing.
#
# WHAT: measures description + when_to_use per skill and enforces a RATCHET, not a hard cap —
# today's over-budget skills are recorded in a baseline and allowed to stay as they are, but
# nothing may grow past its recorded size and no NEW skill may land over budget. That stops
# regrowth without forcing a rewrite of existing skills.
#
#   scripts/skill-frontmatter-lint.sh              lint against the baseline (the gate)
#   scripts/skill-frontmatter-lint.sh --report     print every skill's cost, sorted; never fails
#   scripts/skill-frontmatter-lint.sh --update     rewrite the baseline from current sizes
#
# Baseline: scripts/skill-frontmatter-baseline.txt  ("<skill> <chars>" per line; # comments ok)
# bash 3.2 compatible (no associative arrays, no mapfile).
set -uo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

SKILLS_DIR="skills"
BASELINE="scripts/skill-frontmatter-baseline.txt"

# Budgets in characters. A skill at or under LISTING_BUDGET is always fine; above it, the skill
# must be baselined and must not have grown. Chosen from the observed distribution: the terse
# task verbs (kit-task-pr, kit-task-pr-merge, kit-task-new) all land comfortably under 300.
LISTING_BUDGET="${KIT_SKILL_LISTING_BUDGET:-500}"

FAIL=0
err()  { echo "x $1"; FAIL=1; }
ok()   { echo "ok $1"; }
note() { echo "  $1"; }

# ---- frontmatter field extraction ------------------------------------------
# Prints the value of a top-level frontmatter field, including folded/block-scalar continuation
# lines (`when_to_use: |`), stopping at the next top-level key or the closing `---`.
fm_field() {
  awk -v key="$2" '
    NR == 1 && $0 == "---" { infm = 1; next }
    !infm { exit }
    $0 == "---" { exit }
    {
      if (index($0, key ":") == 1) {
        grab = 1
        sub("^" key ":[ \t]*", "")
        if (length($0)) print
        next
      }
      if (grab && $0 ~ /^[A-Za-z_][A-Za-z0-9_-]*:/) { grab = 0 }
      if (grab) { sub(/^[ \t]+/, ""); sub(/[ \t]+$/, ""); print }
    }
  ' "$1"
}

# Listing cost = the characters the harness actually keeps resident, newlines collapsed.
listing_chars() {
  local f="$1" d w
  d="$(fm_field "$f" description | tr -d '\n')"
  w="$(fm_field "$f" when_to_use  | tr -d '\n')"
  printf '%s' "${#d} ${#w} $(( ${#d} + ${#w} ))"
}

baseline_for() {
  [ -f "$BASELINE" ] || { echo ""; return; }
  grep -v '^[[:space:]]*#' "$BASELINE" 2>/dev/null \
    | awk -v s="$1" '$1 == s { print $2; exit }'
}

if [ ! -d "$SKILLS_DIR" ]; then
  echo "skill-frontmatter-lint: no $SKILLS_DIR/ directory — nothing to lint"
  exit 0
fi

MODE="${1:-lint}"

# ---- collect ----------------------------------------------------------------
rows=""   # "<total> <desc> <when> <skill>" per line
total_all=0
count=0
while IFS= read -r f; do
  [ -n "$f" ] || continue
  skill="$(basename "$(dirname "$f")")"
  set -- $(listing_chars "$f")
  d="$1"; w="$2"; t="$3"
  rows="${rows}${t} ${d} ${w} ${skill}
"
  total_all=$(( total_all + t ))
  count=$(( count + 1 ))
done < <(find "$SKILLS_DIR" -mindepth 2 -maxdepth 2 -name 'SKILL.md' 2>/dev/null | sort)

if [ "$count" -eq 0 ]; then
  echo "skill-frontmatter-lint: no SKILL.md found under $SKILLS_DIR/"
  exit 0
fi

# ---- --report ---------------------------------------------------------------
if [ "$MODE" = "--report" ]; then
  printf '%-26s %7s %12s %8s\n' skill description when_to_use total
  printf '%s' "$rows" | sort -rn | while read -r t d w s; do
    flag=""; [ "$t" -gt "$LISTING_BUDGET" ] && flag=" <- over ${LISTING_BUDGET}"
    printf '%-26s %7s %12s %8s%s\n' "$s" "$d" "$w" "$t" "$flag"
  done
  echo
  echo "$count skills, ${total_all} chars resident (~$(( total_all / 4 )) tokens every turn)"
  exit 0
fi

# ---- --update ---------------------------------------------------------------
if [ "$MODE" = "--update" ]; then
  {
    echo "# skill-frontmatter-baseline.txt — generated by scripts/skill-frontmatter-lint.sh --update"
    echo "# Skills whose description+when_to_use exceed the ${LISTING_BUDGET}-char listing budget."
    echo "# These are GRANDFATHERED: allowed to stay, but may never grow. Shrink them and re-run"
    echo "# --update to tighten the ratchet. A skill that drops under budget leaves this file."
    echo "#"
    echo "# <skill> <chars>"
    printf '%s' "$rows" | sort -rn | while read -r t d w s; do
      [ "$t" -gt "$LISTING_BUDGET" ] && printf '%s %s\n' "$s" "$t"
    done
  } > "$BASELINE"
  echo "ok wrote $BASELINE ($(grep -cv '^[[:space:]]*#' "$BASELINE") grandfathered)"
  exit 0
fi

# ---- lint (the gate) --------------------------------------------------------
over=0
while read -r t d w s; do
  [ -n "$s" ] || continue
  if [ "$t" -le "$LISTING_BUDGET" ]; then
    # Under budget. If it was baselined, it has been fixed — nudge to tighten the ratchet.
    if [ -n "$(baseline_for "$s")" ]; then
      note "$s is now under budget (${t}) — run --update to drop it from the baseline"
    fi
    continue
  fi
  over=$(( over + 1 ))
  base="$(baseline_for "$s")"
  if [ -z "$base" ]; then
    err "$s: description+when_to_use is ${t} chars, over the ${LISTING_BUDGET}-char listing budget"
    note "this text is resident in EVERY session. Move detail into the SKILL.md body (lazy-loaded),"
    note "or accept it deliberately with: scripts/skill-frontmatter-lint.sh --update"
  elif [ "$t" -gt "$base" ]; then
    err "$s: grew to ${t} chars (baseline ${base}) — always-resident context may not grow"
    note "trim it back to ${base} or below, or re-baseline deliberately with --update"
  fi
done < <(printf '%s' "$rows" | sort -rn)

if [ "$FAIL" -eq 0 ]; then
  ok "skill frontmatter within budget ($count skills, ~$(( total_all / 4 )) tokens resident; $over grandfathered)"
fi
exit "$FAIL"
